### ISSUE TITLE
Please make a release to not force users to replace their Arch packages to build AUR packages

### ISSUE THREAD

**Issue by redtide** [lxqt/xdg-desktop-portal-lxqt#1]
I know this is an Arch related issue but it would be solved by creating a tagged release:

Problem:
Recently `libfm-qt-git` and  `lxqt-qtplugin-git` was added as dependencies in the `xdg-desktop-portal-lxqt-git` AUR package.
- `libfm-qt-git` depends on `lxqt-build-tools-git`, not a big problem to replace the `0.10.0-1` (which at the moment are the same), but still I prefer to keep the one in the official Arch repository.
- `lxqt-qtplugin-git` requires at least `libqtxdg-git` that requires me to replace a lot of system packages with the `-git` ones, which to me it's not ideal for 2 reasons:
- I would like to keep a stable release
- I don't want to rebuild packages from AUR

Possible solution:
Doing a first release and create a new non git AUR package using the current LXQt release' dependencies.

**Comment by stefonarch** [comment]
I agree, even call it beta. 
I can't comment about installing as I use direct compiling on arch. On debian the situation is good as there are no deps  on other portals
https://packages.debian.org/bullseye/xdg-desktop-portal

To avoid the dependeciesof libfm-qt-git ecc just edit the PKGBUILD

**Comment by palinek** [comment]
Released..

**Comment by redtide** [comment]
Thank you!
