### ISSUE TITLE
Cannot print in Firefox and Thunderbird

### ISSUE THREAD

**Issue by dglent** [lxqt/xdg-desktop-portal-lxqt#12]
When i set the widget.use-xdg-desktop-portal to True i cannot print (nothing happens when i press print), if i switch back to widget.use-xdg-desktop-portal = False, it works again
My printer is HP
I built xdg-desktop-portal-lxqt with KF5 5.76.0 (_i built with lxqt 1.1.0 in mageia 8, do you think that it has an impact ?_)
The file manager dialogue works fine

**Comment by tsujan** [comment]
See https://bugs.kde.org/show_bug.cgi?id=447106 for the same problem under KDE. It leads to https://bugzilla.mozilla.org/show_bug.cgi?id=1746559

**Comment by tsujan** [comment]
Can you reproduce the issue with Firefox 100.0 too? (I can't test because I don't use xdg desktop portal.)

**Comment by stefonarch** [comment]
I cannot reproduce it, with FF 100 and below, printing always worked.

**Comment by tsujan** [comment]
> ... printing always worked.

Real printing or making PDF?

**Comment by stefonarch** [comment]
Both, but real printing not tested on the laptop yet.

**Comment by tsujan** [comment]
Firefox's version in now 103. Still a problem?

**Comment by dglent** [comment]
From my side i cannot test , i have Firefox 91.12.0esr yet (problem still present)

**Comment by stefonarch** [comment]
Finally tested real printing, arch+firefox 104 and debian 102.1 no issues.

**Comment by dglent** [comment]
I tested with Thunderbird and Firefox 102.2.0 and it is OK now
