### ISSUE TITLE
Firefox save as dialog filename editing broken

### ISSUE THREAD

**Issue by toeserve** [lxqt/xdg-desktop-portal-lxqt#14]
When using Firefox snap on LXQT the file save as dialog box will not let you edit the filename, If you try to type into the filename box with the filename to save as instead a search box pops up taking focus and you are unable to get focus on the save as file name since whenever you try to edit the filename that search box pops up. Perhaps the wrong file picker dialog box is being used.

**Comment by oSoMoN** [comment]
(this was also reported [here](https://forum.snapcraft.io/t/firefox-unable-to-edit-filename-to-save-as/31081) and [there](https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1981148))

**Comment by stefonarch** [comment]
True. I wonder if  the issue persists if
1. the ppa  which ports to  LXQT 1.1.0 is used _and_
2. if in firefox `widget.use-xdg-desktop-portal.file-picker` in `about:config` is set to 1 (necessary to use the LXQt file dialog)

**Comment by stefonarch** [comment]
Looked at my Lubuntu  22.04 with ppa for LXQt 1.1.0 and firefox snap
* by default there was installed  `xdg-desktop-portal-kde` and editing in save dialog worked.
* replaced it with  `xdg-desktop-portal-lxqt` and also there: editing works.

**Comment by tsujan** [comment]
> So it looks it's broken only un the default gtk file dialog.

Then, this can be closed.

**Comment by oSoMoN** [comment]
@toeserve can you confirm that when you observed the issue, the default gtk file dialog was being used, and that installing the lxqt one fixes the problem?

**Comment by toeserve** [comment]
@oSoMoN This is Ubuntu, and it looks like xdg-desktop-portal-lxqt is not in the package repository. So, the gtk one is being used. If the lxqt one will fix this, then I will have to figure out how to get that installed, and hope maybe its included in a future Ubuntu release.

**Comment by toeserve** [comment]
I don't have xdg-desktop-portal-lxqt running or installed, so this bug is in the wrong place probably. I apologize about that

**Comment by stefonarch** [comment]
As said: ubuntu 22.04 with the ppa provides the package.
https://t.co/wxbY3xOMvV

**Comment by oSoMoN** [comment]
I have added a lubuntu-meta bug task to [the bug report on Launchpad](https://launchpad.net/bugs/1981148).

**Comment by anibalsanchez** [comment]
A similar bug has been reported here (it also affects Chrome and Chromium): https://bugs.launchpad.net/ubuntu/+source/ubuntu-unity-meta/+bug/1972130

**Comment by alextz** [comment]
On an Ubuntu 22.04 (newly updated from 18.04) box I got Firefox and Chromium browser back to using the good, system SaveAs dialog box instead of the horrid (((search box focus grabber and almost impossible to change file name from the default))) dialog box by doing this:

`sudo snap install snapd`

This version of snapd, 2.38.3, apparently overrides the apt-installed snapd version 2.38.

That the snap version of snapd wasn't installed ("`snap list`" did not list it) was the glaring difference between the bad box and a laptop that did not have the problem.
