### ISSUE TITLE
If multiple portals installed others will be  chosen first

### ISSUE THREAD

**Issue by stefonarch** [lxqt/xdg-desktop-portal-lxqt#2]
I'm not sure if this is in our reach, but having more than one xdg.-desktop-portal in ` /usr/share/xdg-desktop-portal/portals/` the order of use in the system is  `gtk → kde →  łxqt`.

It should be made sure  that environment variables are respected.
```
XDG_MENU_PREFIX=lxqt-
DESKTOP_SESSION=lxqt
QT_QPA_PLATFORMTHEME=lxqt
QT_PLATFORM_PLUGIN=lxqt
```

**Comment by redtide** [comment]
flatpak/xdg-desktop-portal#656

**Comment by stefonarch** [comment]
Thanks, closing this.
