### ISSUE TITLE
The forced `QT_QPA_PLATFORMTHEME` variable prevents Kvantum users from having their themes correctly set in the file picker

### ISSUE THREAD

**Issue by e-tho** [lxqt/xdg-desktop-portal-lxqt#22]
Kvantum requires `QT_QPA_PLATFORMTHEME` and `QT_STYLE_OVERRIDE` to be set to `qt5ct` and `kvantum` respectively. Being a Hyprland user who chose PcmanFM-Qt as my file manager, I would like to have more visual consistency, especially regarding the file picker, so I would like to use xdg-desktop-portal-lxqt in conjunction with xdg-desktop-portal-hyprland (-wlr fork). LXQt being the most modular and lightest desktop environment in terms of dependencies, its components are for me the best choices for users of wayland compositors/Xorg window managers, its compatibility with them would be greatly appreciated.

**Comment by tsujan** [comment]
> Kvantum requires...

Any widget style needs those EVs.

But why `qt5ct`?  `qt5ct` should **not** be used in DEs that have their own Qt plugins, like LXQt and KDE. It's a third-party program (and a good one) to be used in DEs without a plugin, especially GTK DEs.

**Comment by e-tho** [comment]
It is Hyprland that requires this variable to be set to qt5ct in this case. From a desktop environment point of view you are totally right but it makes xdg-desktop-portal-lxqt incompatible when used with a Wayland compositor and a theme manager such as Kvantum. Of course this is a niche use case and I would understand if it is not considered

**Comment by e-tho** [comment]
> EDIT: Oh, you said Hyprland. Although you could use LXQt's plugin there too (`QT_QPA_PLATFORMTHEME`→`lxqt`).
Ok then, I'll try this

**Comment by tsujan** [comment]
> Ok then, I'll try this

You need to choose your style (Kvantum in this case) in LXQt first.

**Comment by stefonarch** [comment]
FYI: https://github.com/stefonarch/LXQt-Wayland-files#hyprland-tiling

The filepicker works fine but the `lxqt-desktop-portal` doesn't work (e.g. in firefox) - or I didn't find a way.

**Comment by tsujan** [comment]
> but the lxqt-desktop-portal doesn't work 

Does it work in Wayfire?

**Comment by stefonarch** [comment]
Nowhere under wayland afaik.

**Comment by e-tho** [comment]
So I installed `lxqt-config`, defined my settings in appearance and then changed the `QT_QPA_PLATFORMTHEME` variable to `LXQt`, the Kvantum theme is now being used in the file picker but neither the defined font nor my icon theme are used in Qt applications. Am I missing a LXQt component?

**Comment by tsujan** [comment]
> the Kvantum theme is now being used in the file picker

Then we can close this.

> but neither the defined font nor my icon theme are used in Qt applications

This is rather about Hyprland. Try to set `XDG_CURRENT_DESKTOP` to `LXQt`. That is possible in Wayfire (indirectly). You can test it with command line first: `export XDG_CURRENT_DESKTOP=LXQt && QtApp`

@stefonarch even starts an LXQt Session under Wayland compositors (see https://github.com/stefonarch/LXQt-Wayland-files) but by applying patches.

**Comment by tsujan** [comment]
> Am I missing a LXQt component?

I don't know. You especially need `lxqt-qtplugin` and `libqtxdg`.

**Comment by e-tho** [comment]
It was indeed lxqt-qtplugin, thanks

**Comment by pd2s** [comment]
@e-tho , did you manage to run file picker with native wayland? For me it is running under xwayland and completely ignores env vars (QT_SCALE_FACTOR, QT_QPA_PLATFORM, etc)

**Comment by e-tho** [comment]
@pd2s,
I hadn't checked when I was using this configuration, I've since discovered `xdg-desktop-portal-shana` which allows me to have the theme correctly recognized while using `qt5ct` or `qt6ct`. So I've uninstalled `lxqt-config` and `lxqt-qtplugin` as I prefer this modular approach. With my current configuration, the file selector runs with native Wayland

**Comment by e-tho** [comment]
@tsujan,

I necro this but can you please reconsider avoiding forcing the variable to make this portal compatible with `qtct` ? Kvantum is not a problem here, I was mistaken.

I use `pcmanfm-qt`, `xdg-dekstop-portal-lxqt` and `lxqt-policykit` independently of the LXQt desktop environment and only `xdg-dekstop-portal-lxqt` causes problems with `qtct` because of this forced variable, my icon theme is not recognized so the icons are not displayed. 

I switched from Arch Linux to NixOS recently and ran into this problem again when replicating my configuration, plus my previous workaround `xdg-desktop-portal-shana` is not packaged on NixOS. 

I'd like to be able to continue using these components independently of the rest of the desktop environment.

**Comment by e-tho** [comment]
> FYI: https://github.com/stefonarch/LXQt-Wayland-files#hyprland-tiling
> 
> The filepicker works fine but the `lxqt-desktop-portal` doesn't work (e.g. in firefox) - or I didn't find a way.

@stefonarch,

Creating `~/.config/xdg-desktop-portal/portals.conf` with this content could fix this. By default, Hyprland sets it to `hyprland;gtk`.
```
[preferred]
default=hyprland;lxqt
```

**Comment by stefonarch** [comment]
@e-tho : you're my hero, created that file with only```
[preferred]
default=lxqt
```
and it work both in thunderbird and firefox. I heard about that that it was even needed on x11 but didn't investigate.

**Comment by stefonarch** [comment]
This config file was introduced [last May](https://github.com/flatpak/xdg-desktop-portal/pull/955#issuecomment-1538212654), before the portals were chosen in alphabetic order. If I got the [spec](https://flatpak.github.io/xdg-desktop-portal/docs/portals.conf.html) right with multiple sessions installed the filename should be `lxqt-portals.conf`

Updated the wiki https://github.com/lxqt/lxqt/wiki/ConfigMiscellaneous#lxqt-filedialog-in-gtk-applications

**Comment by GotekSC** [comment]
@e-tho
> [...] I've since discovered `xdg-desktop-portal-shana` which allows me to have the theme correctly set while using `qt5ct` or `qt6ct`. So I've uninstalled `lxqt-config` and `lxqt-qtplugin` as I prefer this modular approach. With my current configuration, the file picker runs with native Wayland

As I understand xdg-desktop-portal-shana made it so the file picker of xdg-desktop-portal-lxqt summoned through shana was styled with your qt5ct/qt6ct/kvantum theme, right?
If so, how did you manage to do that?

file: hyprland-portals.conf
```
[preferred]
default=hyprland;shana
org.freedesktop.impl.portal.FileChooser=shana
```
file: config.toml
```
open_file = "Lxqt"
save_file = "Lxqt"

[tips]
open_file_when_folder = "Lxqt"
```
```
$ echo $QT_QPA_PLATFORMTHEME
qt6ct
```
kvantum-dark set in qt6ct
catppuccin theme is set in kvantum

**Comment by e-tho** [comment]
@GotekSC 
I have since switched to `nautilus` and `xdg-desktop-portal-gtk`. I tried `xdg-desktop-portal-shana` again without success when it was packaged on NixOS, and looked no further. I would have preferred `pcmanfm-qt` with the LXQt portal, but this issue makes it hostile to use outside the DE.

**Comment by izmyname** [comment]
I'm surprised xdp-lxqt doesn't work with qt6ct theme out of the box, although pcmanfm-qt does. Are there any chances for qt6ct support ootb, without changing environment variables? xdp-lxqt looks like a great desktop-agnostic solution.

**Comment by tsujan** [comment]
> Are there any chances for qt6ct support

That doesn't have any meaning. Anywhere, only one Qt plugin can be active, and LXQt has its own. Qt plugins are controlled by EVs, and LXQt sets the appropriate EVs for starting an LXQt session — like KDE does for KDE.

Also see `LXQt Session Settings → Environment`. You could set an EV for another Qt plugin there, but please don't report its probable problems to LXQ (no symbolic SVG icons. this or that LXQt setting not being applied, etc.).

**Comment by izmyname** [comment]
This solution implies the usage of full lxqt session or installation of lxqt-config with quite a few deps. I'm talking about using just xdp-lxqt as a desktop-agnostic file chooser, just like pcmanfm-qt which, as I said above, does support qt6ct theming and, because of that, has a great portability.

**Comment by tsujan** [comment]
We don't have a component called "xdp-lxqt". If you mean LXQt file dialog, it's a part of libfm-qt and should be called by the code of the Qt plugin, as in `lxqt-qtplugin`. pcmanfm-qt is a stand-alone app that doesn't need to be called by any plugin.

Again, none of these things is specific to LXQt. GTK file dialog is called by GTK, and KDE file dialog by KDE's Qt plugin. The difference between GTK and Qt is that Qt has a flexible plugin system.
