### ISSUE TITLE
firefox needs .conf file manually created to work

### ISSUE THREAD

**Issue by Bluey26** [lxqt/xdg-desktop-portal-lxqt#23]
Hello.

I was trying to test this feature, to see how different was from the normal (gtk) file dialog firefox uses.
After some steps the program works, but besides the instructions provided in the readme.md file, this was needed:

create `portals.conf` inside `~/.config/xdg-desktop-portal` (`xdg-desktop-portal` folder was created too).

Inside portals.conf:

```
[preferred]
default=gtk
org.freedesktop.impl.portal.FileChooser=lxqt
```

After following the steps found in the README.md and doing this, rebooting and launching firefox makes the function to work properly.

---

Summarized steps:
Install `xdg-desktop-portal-lxqt`

In `about:config` inside `firefox`, set:

`widget.use-xdg-desktop-portal.file-picker` = 1
`widget.use-xdg-desktop-portal.mime-handler` = 1

Create the file and folder detailed previously.
Reboot the system and `firefox` should use the lxqt file manager (pcmanfm-qt)

Info:
```
OS: Arch Linux
Firefox version: 119.0
LXQt Version: 1.3.0
```

---

Maybe the file is generated in other distributions, i have not tested that. Just wanted to mention this for those in the same situation.

Bluey.

**Comment by liu2g** [comment]
Can confirm this method works for me. This problem must be new, I did not need to make the conf file previously and it has been working fine for me for long time until recently.
