### ISSUE TITLE
copy paste full file path?

### ISSUE THREAD

**Issue by deskoop** [lxqt/xdg-desktop-portal-lxqt#26]
Hi, I am sorry if this does not belong here, I am not sure where to ask about this and which part of my system is responsible.

Some time ago, I used to make extensive use of copy/paste full path+filename both to open and to save files. For example, let's imagine  I have MyApplication running and I need to open my file which is in `/path/to/my/file.ext`
So what I did was go to my file browser, copy the exact path+filename of the file, then go back to MyApplication and simply paste the path+filename into the `Open` dialog, then press enter. Similarly, when I wanted to save any file in any location on my hard drive I just pasted the full path+filename into the `Save As` dialog.

However, for some reason, this does not work anymore. I don't know what changed.
As it is right now, I have to do 2 separate things each time:
1) paste the path into the path bar
![image](https://github.com/lxqt/xdg-desktop-portal-lxqt/assets/36651277/a5bbc6eb-e936-4837-a8dd-1d5aba7da809)

2) paste the file name into the `file name` text box.

If I try to do the 'old way' (pasting the full path+filename into the `file name` directly into the text box), nothing happens (and the dialog is closed, without any warning or message).

This took away one of the happiest moments of my workflow: just copy and paste the full path+filename and you're good to go. And now it turned into a longer, two steps for such a simple task as opening or saving a file.

Is this related to the file dialog here? or where can I look for the problem? any suggestions are welcome :)

**My system**
Lubuntu
Desktop: LXQt 1.4.0 
Distro: Ubuntu 22.04.3 LTS (Jammy Jellyfish)

**Comment by stefonarch** [comment]
If that ever worked it was bug IMO. It says: "Filename" at the bottom and not "Path to your file".

Using a path works very fine in terminal windows: `application /path/to/file.extension`, consider to use that.

**Comment by tsujan** [comment]
> However, for some reason, this does not work anymore. 

Most probably, you used GTK file dialog with a GTK app. With `xdg-desktop-portal-lxqt`, you use LXQt file dialog, which distinguishes between paths and filenames.

**Comment by deskoop** [comment]
@stefonarch Thanks for letting me know what the dialog says!! I am grateful for finding someone who can read.
I will certainly not consider using the terminal windows: it will take longer than the 2-steps procedure I just explained... but again, you were busy telling other people what the dialog says.
Honestly, you could have just closed the issue without words and your contribution would be exactly the same.

@tsujan thanks for your comment, that is a good point.

And thanks everyone for your work on LXQt!!!
