### ISSUE TITLE
Version 1.0.0 is requiring Qt5X11Extras in CMakeLists.txt

### ISSUE THREAD

**Issue by romildo** [lxqt/xdg-desktop-portal-lxqt#32]
Does `xdg-desktop-portal-lxqt-1.0.0` still depend on `Qt5X11Extras`? It is still required in [CMakeLists.txt](https://github.com/lxqt/xdg-desktop-portal-lxqt/blob/5b80e66a4ffb25df4029f0309fe81537eed30754/CMakeLists.txt#L21).

**Comment by tsujan** [comment]
Good question. No, it shouldn't depend on Qt5X11Extras. We should remove it from the cmake file and release 1.0.1. Thanks!
