### ISSUE TITLE
zoom GUI does not start with xdg-desktop-portal-lxqt installed

### ISSUE THREAD

**Issue by jp-um** [lxqt/xdg-desktop-portal-lxqt#45]
Pretty much what the subject says.  I am on arch linux using `xdg-desktop-portal-lxqt 1.1.0-1`.

If I have this package installed the zoom GUI never comes up (I am attaching an strace log
[zoom.strace.txt](https://github.com/user-attachments/files/17771189/zoom.strace.txt)).  I uninstall it and zoom starts working again.  

More details in this forum thread: https://bbs.archlinux.org/viewtopic.php?id=300519

Apologies if this in not the right place for this. On the forum they suggested I let you know about this.

**Comment by palinek** [comment]
IMO, this is for zoom's developers investigation. We don't know, what portal interfaces zoom needs and/or checks and how it does it. `xdg-desktop-portal-lxqt` just provides the _org.freedesktop.impl.portal.FileChooser_ as it is stated in _/usr/share/xdg-desktop-portal/portals/lxqt.portal_

**Comment by tsujan** [comment]
Closing this because it's Zoom's problem, but feel free to add comments if you find more info.
