### ISSUE TITLE
Firefox and Thunderbird in LXQt use PCManFM-Qt only once after opening either app

### ISSUE THREAD

**Issue by Vandino86** [lxqt/xdg-desktop-portal-lxqt#48]
### Steps to reproduce:
1. Ensure that at least `xdg-desktop-portal` 1.18.4 and `xdg-desktop-portal-lxqt` 1.1.0 are installed (see Notes for additional portals).
2. Ensure that the file `~/.config/xdg-desktop-portal/lxqt-portals.conf` exists and consists of the following:
```
[preferred]
default=lxqt
```
3. In `about:config` in Firefox 133.0, ensure that `widget.use-xdg-desktop-portal.file-picker` and `widget.use-xdg-desktop-portal.mime-handler` are both set to `1` and that the other three `widget.use-xdg-desktop-portal` settings (`widget.use-xdg-desktop-portal.location`, `widget.use-xdg-desktop-portal.open-uri`, and `widget.use-xdg-desktop-portal.settings`) are all set to `2`.
4. Reboot the system if you changed and/or (re-)installed any of the above.
5. Open Firefox to any webpage (such as duckduckgo.com).
6. Press Ctrl+S. PCManFM-Qt should appear as the save dialog, like expected.
7. Close the PCManFM-Qt save dialog (no need to save the webpage).
8. Press Ctrl+S again. The GTK dialog appears instead.
9. Close the GTK save dialog.
10. Repeat step 8-9 however many times you'd like. The GTK dialog will always appear until all Firefox windows are closed and a new window is opened, starting a new Firefox session. The same thing will happen with this new session (the first time Ctrl+S is used, PCManFM-Qt is used for the dialog, but the GTK dialog is used every time after that).

### Notes:
* In addition to `xdg-desktop-portal` 1.18.4 and `xdg-desktop-portal-lxqt` 1.1.0, I also have `xdg-desktop-portal-gtk` 1.15.1 and `xdg-desktop-portal-kde` 6.2.0 installed.
* This same exact issue occurs in Firebird 128.4.2esr with the same settings (Settings --> General --> Config Editor --> `widget.use-xdg-desktop-portal.file-picker` and `widget.use-xdg-desktop-portal.mime-handler` = `1`, other three `widget.use-xdg-desktop-portal` settings = `2`).
* This may be an issue on Firefox's and Thunderbird's side, but I'm not entirely sure.
* I couldn't reproduce this in Discord (Flatpak), Caprine (Flatpak), or Telegram. They all opened PCManFM-Qt for saving or uploading every time.
* LibreOffice seems to only use GTK dialogs when Options --> LibreOffice --> General --> Open/Save Dialogs --> "Use LibreOffice dialogs" is unchecked. Even `GTK_USE_PORTAL=1 libreoffice` won't get it to use PCManFM-Qt as suggested in [the wiki](https://github.com/lxqt/lxqt/wiki/ConfigMiscellaneous#lxqt-filedialog-in-gtk-applications), though it states that this works for only _some_ other GTK apps. Maybe LibreOffice is hard-coded to use GTK dialogs and I have no other choice? Oh well.

### System Info:
Distro: Void Linux (x86-64 musl)
Linux Version: 6.6.63
LXQt Version: 2.1.0
Qt Version: 6.7.0

**Comment by tsujan** [comment]
Some notes:

> Ensure that the file ~/.config/xdg-desktop-portal/lxqt-portals.conf exists

It isn't needed anymore.

> PCManFM-Qt should appear as the save dialog

It's libfm-qt. pcmanfm-qt has nothing to do with LXQt file dialog.

> LibreOffice seems to only use GTK dialogs

Here LibreOffice uses Qt's default file dialog and has a Qt skin.

Years ago, we had a discussion with LibreOffice's devs and agreed that they should use Qt's default file dialog instead of LXQt file dialog under LXQt. The reason was that they changed the dialog in their codes.

**Comment by Vandino86** [comment]
I got rid of the `~/.config/xdg-desktop-portal/` dir entirely. This didn't affect anything. However, I found out that running Firefox using `GTK_USE_PORTAL=1` (`GTK_USE_PORTAL=1 firefox` in a terminal) seems to "fix" this issue. I put "fix" in quotes because I consider it to be more of a workaround, but at least it uses libfm-qt for the save/open dialogs every time during the whole session when run like this. This "fix"/workaround also works for Thunderbird.

**Comment by tsujan** [comment]
Is Firefox installed normally in your system, or by a method like flatpak?

**Comment by Vandino86** [comment]
> Is Firefox installed normally in your system, or by a method like flatpak?

It's installed normally (via XBPS). It's not Flatpak.

**Comment by Vandino86** [comment]
I made a bug report on Firefox's bugtracker (https://bugzilla.mozilla.org/show_bug.cgi?id=1936463). It's an issue on Firefox/Thunderbird's side. I was able to reproduce this issue in KDE Plasma as well.
