### ISSUE TITLE
Settings saved/applied using the plain libfm-qt's file dialog

### ISSUE THREAD

**Issue by palinek** [lxqt/xdg-desktop-portal-lxqt#7]
##### Expected Behavior
File dialog provided by xdg-desktop-portal-lxqt should behave the same way as the LXQt native file dialog in Qt apps.

##### Current Behavior
With current implementation we don't use the `Fm:FileDialogHelper` and loosing its functionality, e.g. applying & saving preferences.

##### Possible Solution
Make use of the `Fm:FileDialogHelper` to not copy-paste its logic into our code. 

##### Steps to Reproduce (for bugs)
1. invoke open/save dialog
2. change some settings (size, icon sizes, etc.)
3. close dialog
4. invoke open/save dialog & observe previous settings lost

##### Context
I will submit PRs for libfm-qt, and xdg-desktop-portal-lxqt

##### System Information
* xdg-desktop-portal-lxqt Version: git master
* libfm-qt Version: git master

**Comment by stefonarch** [comment]
Actually here setting are all preserved on reopening (with libfm-qt helper-extend-api)

**Comment by stefonarch** [comment]
I noticed that now localization is broken: english and smaller window. no clue when this started. Rebooted also.
