### ISSUE TITLE
Lost localization

### ISSUE THREAD

**Issue by stefonarch** [lxqt/xdg-desktop-portal-lxqt#9]
Looks like introduced by https://github.com/lxqt/xdg-desktop-portal-lxqt/commit/e6121bb667e92397f5edcf314ac79484e4ebf4ee, compiling https://github.com/lxqt/xdg-desktop-portal-lxqt/commit/fcd6077020d9de9c040d756b047b532464054bfb localization works.

**Comment by palinek** [comment]
Yes... that's what is #8 addressing.

**Comment by stefonarch** [comment]
I missed that PR, works again with that branch.
